from flask import Flask, render_template, request, jsonify 
import os 
from ocr import extract_text
from ai_engine import get_answer 
from retriever import find_similar_question
import base64 

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/solve', methods=['POST'])
def solve():
    if 'image' not in request.files:
        return jsonify({"error": "No image uploaded"}), 400

    image = request.files['image']
    image_path = "temp_upload.png"
    image.save(image_path)

    try:
        # Step 1 - OCR
        question = extract_text(image_path)

        if not question or len(question.strip()) < 10:
            return jsonify({"error": "Could not extract text from image. Please try a clearer image."}), 400

        # Step 2 - Retrieval first
        match = find_similar_question(question)

        if match:
            similarity = round(match['similarity'], 3)

            # High confidence match
            if similarity >= 0.75:
                confidence = "HIGH"
                confidence_msg = "Exact or very close match found in verified database."
            # Medium confidence match
            elif similarity >= 0.60:
                confidence = "MEDIUM"
                confidence_msg = "Similar question found. Please verify the answer."
            # Low confidence — use LLM instead
            else:
                confidence = "LOW"
                match = None

            if match:
                return jsonify({
                    "question": question,
                    "answer": f"Correct Option: {match['correct_answer']}",
                    "explanation": match['explanation'],
                    "source": match['source'],
                    "method": "database",
                    "similarity": similarity,
                    "confidence": confidence,
                    "confidence_msg": confidence_msg
                })

        # Step 3 - Fallback to LLM
        ai_answer = get_answer(question)
        return jsonify({
            "question": question,
            "answer": "",
            "explanation": ai_answer,
            "source": "Llama 3.2",
            "method": "ai",
            "similarity": 0,
            "confidence": "AI",
            "confidence_msg": "No database match found. Answer generated by AI — please verify."
        })

    except Exception as e:
        return jsonify({"error": str(e)}), 500

    finally:
        if os.path.exists(image_path):
            os.remove(image_path)
            
if __name__ == "__main__":
    app.run(debug=False, port=5000)